### ISSUE TITLE
İyileştirme:

### ISSUE THREAD

**Issue by FatihcanUslu** [ttbilgin/PyNar_Hata_Raporlama#11]
(Bu yeni özellik önerisi Windows 10 işletim sistemi içindir.)

Yukarı ve aşağı butonları zaten en yukarıdaysak yada zaten en aşağıdaysak görünürlükleri kapatılabilir. Bu sayede kullanıcı bir özellik arıyorken modülün en üstünde olduğunu yada en aşağısında olduğunu daha rahat anlar.

![buton](https://user-images.githubusercontent.com/72496488/162420690-026109de-7f7b-4a05-a47e-40c7f042ebd0.PNG)
.

**Comment by aysegul-hatipoglu** [comment]
özellik eklendi.
