### ISSUE TITLE
Hata:

### ISSUE THREAD

**Issue by FatihcanUslu** [ttbilgin/PyNar_Hata_Raporlama#12]
(Bu hataya Windows 10 işletim sisteminde rastlanmıştır.)

İçe aktarım hatasının sebebi cv2 kütüphanesinin yüklenmemiş olmasıydı. Ancak chatbot import yanlış yazıldı hatası döndürüyor

![hata](https://user-images.githubusercontent.com/72496488/162424408-cbb811a7-f683-47dd-9bb3-27607079831d.PNG)
.

**Comment by ttbilgin** [comment]
Chatbot hata düzeltme algoritmasında yaptığımız iyileştirme ile bu tür hatalarda  x paketi kurulu değil şeklinde bildirim veriyoruz. 
Bu hata düzeltildi.
