### ISSUE TITLE
İyileştirme:

### ISSUE THREAD

**Issue by abdullahbilgi** [ttbilgin/PyNar_Hata_Raporlama#13]
(Bu yeni özellik önerisi Windows 10 işletim sistemi içindir.)

Yanlış bir kod yazınca java'daki gibi yanlış  yapılan yerin altı kırmızı tırtıklı çizgi ile çizilebilir. Yada yanlış yazılan yerin yanında intellij idea gibi info box çıkartıp anında yanlış yapılan yeri düzelttirilebilir.  
![Ekran Görüntüsü (11)](https://user-images.githubusercontent.com/92636172/162535953-5ff22ffb-bbdd-48b4-9e7a-ff5bb8b12bf4.png)

**Comment by ttbilgin** [comment]
Güzel bir öneri, teşekkürler @abdullahbilgi  bunu özellik listesine ekliyorum, tabiki bu sürümde yapabilirmiyiz bakacağız, bunu gerçek zamanlı yapabilmek için sürekli olarak kodu kontrol etmek gerekiyor, bu durum CPU kullanımını arttırıyor.

**Comment by ttbilgin** [comment]
Bu geliştirmeyi yeni sürümde değerlendireceğiz, bu sürümde bunu yapmak çok vakit alıcı olacak.
