### ISSUE TITLE
Yeni Özellik:

### ISSUE THREAD

**Issue by abdullahbilgi** [ttbilgin/PyNar_Hata_Raporlama#15]
(Bu yeni özellik önerisi Windows 10 işletim sistemi içindir.)

Yardım robotunda tek tek hatalı satırları düzeltmek butonunun yanına bulunan tüm hataları tek seferde düzelten buton koyulabilir

![Ekran Görüntüsü (11)](https://user-images.githubusercontent.com/92636172/162536941-e7b466bf-ffbd-4329-9066-87c33e7b9c61.png)
.

**Comment by ttbilgin** [comment]
@abdullahbilgi  Yardım robotu yapsı gereği bir seferde sadece 1 hata tespit edebiliyor, onu başarıyla düzeltebilirse ve kodun o satırı sorunsuz çalışırsa sonraki hata satırını düzeltmeye çalışır. Hepsini aynı anda düzelttirmeye kalkışırsak kodu daha fazla bozabiliriz.
