### ISSUE TITLE
Hata:

### ISSUE THREAD

**Issue by sagumax404** [ttbilgin/PyNar_Hata_Raporlama#19]
(Bu hata ile  Windows 10' da karşılaşılmıştır) 
Ayarlara girdiğim zaman punto değerini değiştirmediğim halde şuanki olan punto değerini kendisi her seferinde 2 birim azaltıyor. Ayrıca effects bölümündeki seçenekleri açıp editörü yeniden başlattığımda herhangi bir değişiklik olmuyor. 
![hata](https://user-images.githubusercontent.com/90527001/162567183-e75b124e-ec6e-4daf-b8fe-ef9e5aad7014.png)
![hata2](https://user-images.githubusercontent.com/90527001/162567211-4aea531a-9b10-4248-98c1-ba089d5b4cc9.png)

**Comment by aysegul-hatipoglu** [comment]
Problem çözüldü.
