### ISSUE TITLE
İyileştirme:

### ISSUE THREAD

**Issue by sagumax404** [ttbilgin/PyNar_Hata_Raporlama#22]
(Windows 10 işletim sistemi için iyileştirme önerisi)
İleri veya geri alınacak bir şey olmadığı zaman resimdeki oklar tıklanılamaz hale getirilerek belirtilebilir.
![geri ileri](https://user-images.githubusercontent.com/90527001/162576479-607e922d-c2af-4094-8c50-458c8035acbc.png)

**Comment by aysegul-hatipoglu** [comment]
Özelllik eklendi
