### ISSUE TITLE
Yeni Özellik: 

### ISSUE THREAD

**Issue by sagumax404** [ttbilgin/PyNar_Hata_Raporlama#23]
(Bu yeni özellik önerisi Windows 10 işletim sistemi içindir.)
Yardım robotuna mouse'un sol tıkına basarak da mesaj göndermek için resimde belirttiğim dikdörtgen içindeki gibi bir şekil eklenebilir.
![okkkk](https://user-images.githubusercontent.com/90527001/162576950-600b904d-c826-439e-92b1-49457b86faea.png)

**Comment by ttbilgin** [comment]
@sagumax404  öneri için teşekkürler, fakat böyle bir buton koyarsak chatbot'un zaten sağdan soldan ikonlarla daraltılmış olan yazı yazma alanı da çok daralacaktır. Chatbota yazı yazarken zaten klavye kullandıkları için klavyedeki Enter tuşuna basmak fareyi alıp onunla ikona tıklamaktan daha kolay olur.
