### ISSUE TITLE
iyileştirme

### ISSUE THREAD

**Issue by Sanemcoskun** [ttbilgin/PyNar_Hata_Raporlama#24]
![image](https://user-images.githubusercontent.com/92624533/162589898-dd535b1e-eeeb-4f3a-9142-d7851eb53fd6.png)

ilk açıldığında kapatma veya küçültme işaretleri gözükmüyor

![image](https://user-images.githubusercontent.com/92624533/162589928-3099bcb8-3794-4778-8ae6-d9925cb53fd2.png)

ekranı küçülttüğümde geliyor

(windows 8)

**Comment by ttbilgin** [comment]
Gözüküyor ama ekranın üst tarafından kaldığı için göremiyor olabilir misin? Gönderdiğin her iki resimde de pencere kenarlığı var gibi görünüyor.
