### ISSUE TITLE
iyileştirme:

### ISSUE THREAD

**Issue by Sanemcoskun** [ttbilgin/PyNar_Hata_Raporlama#25]
![image](https://user-images.githubusercontent.com/92624533/162590188-757f356d-10d8-4738-aaa3-a2d52b87158e.png)
büyütme küçültmenin yanına eski haline geri dönmesini sağlayan bir buton yapılabilir. örneğin kişi kodu çok büyüttüyse tekrar tekrar küçültmek yerine ilk haline geri döndürme yapabilir

**Comment by ttbilgin** [comment]
@Sanemcoskun öneri için teşekkürler, fakat bunun için fazladan bir buton daha koymamız gerekir, bu da editörün üst menülerini daha sıkışık ve karışık hale getirecektir. Editörü kapatıp açarsa zaten eski haline dönüyor.
