### ISSUE TITLE
Yeni Özellik:

### ISSUE THREAD

**Issue by abdullahbilgi** [ttbilgin/PyNar_Hata_Raporlama#28]
(Bu yeni özellik önerisi Windows 10 işletim sistemi içindir.)

Buraya beni hatırla gibi bir buton eklenebilir ve Pynar'a her giriş yaptığımızda tekrardan oturum açmaya gerek kalmaz
![Ekran Görüntüsü (14)_LI](https://user-images.githubusercontent.com/92636172/162590811-de51b191-9a7c-41b8-bb44-86e19055967e.jpg)
.

**Comment by aysegul-hatipoglu** [comment]
@abdullahbilgi Oturumdan çıkış yapılmadığı sürece tekrar oturum açılması istenmiyor zaten otomatik giriş yapılı bir şekilde geliyor.
