### ISSUE TITLE
İyileştirme:

### ISSUE THREAD

**Issue by abdullahbilgi** [ttbilgin/PyNar_Hata_Raporlama#30]
(Bu yeni iyilestirme önerisi Windows 10 işletim sistemi içindir.)
Buluta dosya yüklediğimiz zaman dosyayı en son kaydettiğimiz yerden alıp belgelerdeki Pynar içine taşıyor.Bunun Yerine Dosyanın Bir yedeğini alıp buluta kaydedebilir.
![Ekran Görüntüsü (15)_LI](https://user-images.githubusercontent.com/92636172/162590977-eb9e35f6-052e-4ab4-abaf-474701b503da.jpg)

**Comment by ttbilgin** [comment]
çalıştığın herhangi bir klasördeki bir py dosyayı buluta yüklediğinde o klasördeki yerel kopya silinmiyor bir yere taşınmıyor. Sadece şu oluyor, o dosyayı buluttan indirirken Belgeler'deki PynarKutu klasörüne indirir. Bunun sebebi indirirken sürekli olarak kullanıcıya yer sormaması içindir. Ama şöyle iyileştirebiliriz.

@aysegul-hatipoglu şu pencereye "Farklı Konuma kaydet" butonu ekleyelim. Kod yine PynarKutu içine kaydedilsin ama buna ek olarak "Farklı konuma kaydet" butonu tıklarsa File Save Dialog açılsın ve kullanıcının seçtiği yere kaydedilsin ve editorde PynarKutudaki değil farklı konuma kaydedilmiş olan açılsın.

![image](https://user-images.githubusercontent.com/854154/165385788-eaadcd3e-ba81-4522-bac0-0244dae37fe8.png)

**Comment by aysegul-hatipoglu** [comment]
@ttbilgin ekledim Hocam
