### ISSUE TITLE
İyileştirme:

### ISSUE THREAD

**Issue by cagrigonultas** [ttbilgin/PyNar_Hata_Raporlama#34]
(Bu iyileştirme Wİndows ve Lİnux/Ubuntu için yazılmıştır.)
Robotdan kod hatası için yardım alındığında ctrl+z ile tekrar geriye dönülemiyor.
![Ekran Görüntüsü - 2022-04-09 23-58-36](https://user-images.githubusercontent.com/91600415/162591620-b64ea9c8-017c-4c64-b9bd-84ae7c13269e.png)

**Comment by aysegul-hatipoglu** [comment]
Problem çözüldü.
