### ISSUE TITLE
Yeni Özellik

### ISSUE THREAD

**Issue by Sanemcoskun** [ttbilgin/PyNar_Hata_Raporlama#35]
paket yöneticisinde kullanıcı paket ismi girmeye başladığında aşağıda öneriler çıkabilir. böylece kişi tam ismi girmese bile kolayca görebilir

**Comment by ttbilgin** [comment]
@Sanemcoskun teşekkürler, paket adını kullanıcı yazdığında PYPI sitesinde arattığımız için ve oradan bize sadece tek yanıt döndüğü için bunu teknik olarak yapamıyoruz. Öneri getirmek için bütün python paket bilgilerini indirmek gerekir. Bütün python paketlerinin listesini indirip onları güncel tutmak da zor olduğu için teknik olarak bunu yapmak getireceği faydadan daha zor olduğu için yapamıyoruz.
