### ISSUE TITLE
Yeni Özellik:

### ISSUE THREAD

**Issue by yunusefeyilmaz** [ttbilgin/PyNar_Hata_Raporlama#41]
Genellikle çoğu editörlerde ya da uygulamalarda sekmeleri kapatmak için mouse'un orta tuşu kullanılır. Bence bu kullanıcıya daha kolaylık sağlıyor. Bu özellik eklenebilir.
(Windows 10)
![öneri](https://user-images.githubusercontent.com/89478740/162632510-7a4ee099-f73f-47b6-a714-e7be79def6cd.png)

**Comment by aysegul-hatipoglu** [comment]
Eklendi.
