### ISSUE TITLE
iyileştirme

### ISSUE THREAD

**Issue by Sanemcoskun** [ttbilgin/PyNar_Hata_Raporlama#44]
intellij codeblocks gibi parantez, tırnakların bir tanesi yazıldığında diğerleri otomatik tamamlanabilir

**Comment by ttbilgin** [comment]
Teknik olarak Otomatik tamamlayamıyoruz ama kullanıcı parantez veya tırnakları kapatmaz ise buna dair bir bildirim vermeyi editöre ekledik.
