### ISSUE TITLE
İyileştirme:

### ISSUE THREAD

**Issue by OsmanTahirKuzu** [ttbilgin/PyNar_Hata_Raporlama#48]
![image](https://user-images.githubusercontent.com/56130302/163137434-7891df63-6301-4016-a201-9f6e06eaa8e9.png)
Yardım penceresi açıldıktan sonra aynı anda editörü de kullanayım derseniz yapamıyorsunuz. Yardım penceresini kapatmanız gerekiyor. Yardım penceresini kapatmadığınız müddetçe sadece yardım kısmında işlem yapılabiliyor. PyNar'da diğer hiçbir işlem yapılamıyor.

**Comment by aysegul-hatipoglu** [comment]
Yardım penceresine Minimize etme özelliği eklendi.
