### ISSUE TITLE
Yeni Özellik:

### ISSUE THREAD

**Issue by OsmanTahirKuzu** [ttbilgin/PyNar_Hata_Raporlama#49]
![image](https://user-images.githubusercontent.com/56130302/163141785-8daaffd8-12ba-4d71-b940-7dbdb731b7bb.png)
Çalıştır butonuna bastıktan sonra sonuçların ayrı pencerede gözükmesi yerine altta gözükmesi daha güzel olabilir aynı visual studio code'da olduğu gibi. 
![image](https://user-images.githubusercontent.com/56130302/163142567-6f0a23e2-8e52-4278-95c5-3b729c989656.png)

**Comment by ttbilgin** [comment]
@OsmanTahirKuzu  teknik olarak bu sürümde bunu yapmak zor. Çünkü bizim editörümüzün Hem windows hem linuxta çalışması gerekiyor, bu tür bir yapıyı hem linux hem windows için yapabilmek için her ikisine özel olarak kod yazmak gerekiyor malesef.
