### ISSUE TITLE
Yeni Özellik : 

### ISSUE THREAD

**Issue by yunusefeyilmaz** [ttbilgin/PyNar_Hata_Raporlama#50]
Diğer python editörlerinde olduğu gibi ayarlar kısmına hangi python sürümü seçili olduğunu ve klasörünü değiştirme gelebilir.
Kullanıcı istediğinde başka bir python sürümünü kulanabilmeli.
(Windows 10)
Örneğin:
![öneri1](https://user-images.githubusercontent.com/89478740/163246067-ef5e6d13-599e-4806-b214-98731665456f.png)

**Comment by aysegul-hatipoglu** [comment]
![image](https://user-images.githubusercontent.com/13594146/165938257-f0a782fc-7385-42ae-b5f6-0592d6b8fe53.png)

@ttbilgin Hocam pynar editör sürümünün olduğu ekrana python ve qt sürümleri ile alakalı bilgileri ekledim ama @yunusefeyilma 'ın dediği şekilde bir geliştirme yapacak mıyız?

**Comment by aysegul-hatipoglu** [comment]
![image](https://user-images.githubusercontent.com/13594146/165938830-b11870d2-1522-4057-aa93-c42bda0cd196.png)
@ttbilgin Hocam pynar editör sürümünün olduğu ekrana python ve qt sürümleri ile alakalı bilgileri ekledim ama @yunusefeyilmaz  'ın dediği şekilde bir geliştirme yapacak mıyız?

**Comment by ttbilgin** [comment]
@aysegul-hatipoglu  bu konuya haftaya bakacağım

**Comment by ttbilgin** [comment]
Bu özellik eklenmiştir.
