### ISSUE TITLE
Yeni Özellik:

### ISSUE THREAD

**Issue by furkanyaylaz** [ttbilgin/PyNar_Hata_Raporlama#51]
Kullanıcının oturum açarken sürekli mail ve şifresini yazmaması için "oturumu açık tut" seçeneği ve şifreyi yazarken şifreyi görebilmesi için  "şifreyi gizle/göster" butonu eklenebilir.

![sifre_gösterme](https://user-images.githubusercontent.com/92256027/163679886-2d4b832d-93fa-41b3-a639-88a238f7c10e.png)

**Comment by aysegul-hatipoglu** [comment]
@furkanyaylaz oturumdan çıkış yapılmadığı sürece tekrar oturum açılması istenmiyor, zaten otomatik giriş yapılı bir şekilde geliyor. Şifreyi gizle/göster işlemi için checkbox ekledim.
