### ISSUE TITLE
Yeni Özellik :

### ISSUE THREAD

**Issue by abdullahbilgi** [ttbilgin/PyNar_Hata_Raporlama#53]
(Bu yeni özellik Windows 10 içindir)
Ayarların içine bir buton ekleyip ,isteyenler için yazdığımız metin uzun ise sağ tarafa gitmek yerine cümleyi gösterdiğim yerden alt satıra geçerek orada devam ettirebilir.
![Ekran Görüntüsü (33)_LI](https://user-images.githubusercontent.com/92636172/164971621-d97c09f8-3d96-43f6-b576-be7f57eb08fd.jpg)
![Ekran Görüntüsü (34)](https://user-images.githubusercontent.com/92636172/164971627-bb8faef6-e0bf-4e20-884d-41bf73b72435.png)

**Comment by ttbilgin** [comment]
@abdullahbilgi öneri için teşekkürler, fakat Python dilinde noktalı virgül olmadığı için biz o şekilde alt satıra geçirirsek print'e ait satır bozulmuş olacak ve hata verecektir. Senin ekranda hem sağ menü hemde chatbot açık olduğu için alan daralmış bu yüzden görüş sorun oluşabiliyor. Aynı davranış diğer Python editörlerinde de vardır. 

Ama tabiki şunu yaparız, bu hazır örnekteki o satırdaki ifadeyi kısaltarak tekrar düzenleriz.


![image](https://user-images.githubusercontent.com/854154/164981045-8dd7c548-3a9a-48cc-abb7-60813e00877b.png)
