### ISSUE TITLE
Hata :

### ISSUE THREAD

**Issue by abdullahbilgi** [ttbilgin/PyNar_Hata_Raporlama#54]
(Bu hataya Windows 10 da rastlanmıştır)
Yardım robotunda türkçe değil de ingilizce olarak bilgilendirme yapıyor
![Ekran Görüntüsü (37)](https://user-images.githubusercontent.com/92636172/164972159-c344eaab-882c-40d7-8fb5-01ed4a2afa79.png)
![Ekran Görüntüsü (38)](https://user-images.githubusercontent.com/92636172/164972160-fc4b6769-30a3-4c5d-a387-5d9dc77fbe60.png)
![Ekran Görüntüsü (39)](https://user-images.githubusercontent.com/92636172/164972245-f04e0006-f129-4f8f-8825-6c5e510a2e72.png)

.

**Comment by ttbilgin** [comment]
@aysegul-hatipoglu  bu hataların Türkçelerini veritabanına ekleyelim.

**Comment by aysegul-hatipoglu** [comment]
eklendi.
