### ISSUE TITLE
Yeni özellik

### ISSUE THREAD

**Issue by cagrigonultas** [ttbilgin/PyNar_Hata_Raporlama#59]
(Bu yeni özellik önerisi Windows 10 içindir.)
Zero Division Error hatası karşılaşıldığında Türkçe olarak ifade ediliyor.

![hi](https://user-images.githubusercontent.com/91600415/165975890-2e520ed7-04c5-4ebf-b0f4-20069608f925.PNG)

Bu hata except olarak da belirtilebilir mi acaba diye aklıma geldi. Mümkün mü bilmem ama öneri olarak öne sürmek istedim.

![yenilik](https://user-images.githubusercontent.com/91600415/165976266-b89fcaf8-b0cd-4342-8ebb-2ab138d50e39.PNG)
![önerş](https://user-images.githubusercontent.com/91600415/165976286-410e59d9-f3d6-42c2-abab-f96b27ae1320.PNG)

**Comment by aysegul-hatipoglu** [comment]
@cagrigonultas Çağrı tam anlayamadım öneriyi ama sol menüdeki örnekler arasında olmasını mı istiyorsun?
![image](https://user-images.githubusercontent.com/13594146/165980402-b7847da6-1b2d-4eab-b9ba-aac7f0dcf57a.png)

öyle iste sol menüde Try Except örneklerinde mevcut

**Comment by cagrigonultas** [comment]
@aysegul-hatipoglu  yok direkt hatanın adını Türkçe kullanabilir miyiz diye merak etmiştim.  Hani zero division error yerine sıfıra bölme hatası yazmak gibi.

**Comment by aysegul-hatipoglu** [comment]
@cagrigonultas Anladım malesef o şekilde olmaz. Açıklamaları türkçe oluşturmaya özen gösteriyoruz ama direk kod olarak çalıştırdığımız pythona ait ifadeleri değiştiremeyiz  ZeroDivisionError pythona ait bir ifade ama bizim hazır örneklerimizde yorum satırı olarak açıklama olarak ekleyebiliriz.

**Comment by cagrigonultas** [comment]
@aysegul-hatipoglu  Peki o zaman öyle yapalım. Teşekkürler
