### ISSUE TITLE
Hata:

### ISSUE THREAD

**Issue by elifdoylan** [ttbilgin/PyNar_Hata_Raporlama#70]
İşletim Sistemi: Windows 11
Kayıt olduktan sonra editörden bulut işlemleri yapmak istediğimde oturum açmam gerektiğine dair bir mesaj aldım ancak mailimi ve şifremi girdiğimde editör kapandı. Her denediğimde ise editör kapandı ve editörde oturum açamadım.

**Comment by ttbilgin** [comment]
@elifdoylan Sisteme adını ve soyadını girerken arada 2 tane boşluk bırakmışsın, biz bu kadarını öngörmemişiz, bunu yeni sürümde düzeltiyoruz, fakat şimdiki durumda ben aradaki fazladan boşluğu kaldırdım, şuan giriş yapabiliyor olmalısın.

@fatiiates öğrenciler web portalda kendi user_fullname stringlerini değiştirebilsinler, bunun için "Parola Bilgileri" bölümüne bir textbox ekleyelim.

**Comment by fatiiates** [comment]
@ttbilgin, "parola bilgilerinin" altına yeni "kişisel bilgiler" alanı açtım ve oraya ekledim. Şu an öğrenciler isimlerini değiştirebiliyorlar.

**Comment by ttbilgin** [comment]
@fatiiates evet eklemişsin fakat mevcuttaki ad soyad bilgisi textbox'lar içinde gelmiyor.

**Comment by fatiiates** [comment]
@ttbilgin, güncelleme gerçekleştirdim, test edilebilir.
