### ISSUE TITLE
Hata:

### ISSUE THREAD

**Issue by elifdoylan** [ttbilgin/PyNar_Hata_Raporlama#71]
İşletim Sistemi: Windows 11
Paket indirmeye çalıştığımda indiremedim PyPI dan paketi buldu ancak indirmeden sonuç alamadım. Uzun zaman beklememe rağmen indirmenin başarılı olduğuna dair bir ekran göremedim.

**Comment by ttbilgin** [comment]
@elifdoylan hangi pakette oldu bu hata?

**Comment by elifdoylan** [comment]
@ttbilgin AppJar, decorate, jedi, pyautogui gibi birkaç pakette denedim ama indirme başarılı penceresini göremedim. Bu paketleri indirmeyi birkaç kez denedim genellikle indirme ekranında takılı kaldı ama birkaç denememde editör kapandı.

**Comment by ttbilgin** [comment]
bir komut satırı (cmd.exe) aç, komut satırında sadece
path
yaz ve ekrana gelen çıktıyı buraya cevap olarak yaz.

**Comment by elifdoylan** [comment]
PATH=C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\ELİF DOYLAN\AppData\Local\Programs\Python\Python310-32\Scripts\;C:\Users\ELİF DOYLAN\AppData\Local\Programs\Python\Python310-32\;C:\Users\ELİF DOYLAN\AppData\Local\Programs\Python\Launcher\;C:\Users\ELİF DOYLAN\AppData\Local\Microsoft\WindowsApps;C:\Users\ELİF DOYLAN\AppData\Local\Programs\Microsoft VS Code\bin

**Comment by ttbilgin** [comment]
@elifdoylan  pynar editörü programlar bölümünden komple kaldır. Sonra şu resimdeki gibi Windowsta bir pencere açıp %AppData% yazıp açılan klasörde Pynar Kod Editörü klasörünü de silip pynar'ı tekrar kur ve tekrar Paket yöneticisini test et lütfen.

![image](https://user-images.githubusercontent.com/854154/167307348-4e601b9b-220e-474c-9dcc-9677debebe96.png)

**Comment by elifdoylan** [comment]
@ttbilgin Dediğiniz adımları gerçekleştirdim ama aynı sorun hala devam ediyor.

**Comment by ttbilgin** [comment]
elif, pynar açıkken bu durumun bir videosunu çekip linki buraya koyarmısın? 

ayrıca AppJar, decorate, jedi, pyautogui  paketlerini Pynar kapalıyken 
pip install appjar
gibi pip ile kurabiliyormusun?

**Comment by elifdoylan** [comment]
@ttbilgin Kapalıyken denediğimde pip hatası verdi ama o hatayı çözdüm tekrar denediğimde paketleri sorunsuz bir şekilde indirdi.

**Comment by ttbilgin** [comment]
Pynar paketleri kurmak için pip kullanır, bilgisayarında pip düzgün çalışmıyorsa pynarda da paket kurulumu düzgün çalışmaz. Şu an sorun yok sanırım?

**Comment by elifdoylan** [comment]
Sorun kalmadı.
