### ISSUE TITLE
Hata

### ISSUE THREAD

**Issue by emredogangun** [ttbilgin/PyNar_Hata_Raporlama#9]
(Bu hata ile Windows 10'da karşılaşılmıştır.)
Bul ve değiştir butonu kullanımında değiştir kısmında yazdığım kod üzerinde 'print' ifadesi ile 'printf' ifadesini değiştirmeye çalıştığımda ilk print'i printf'e çeviriyor ama diğerlerinde 1 tane 'f' fazladan basıyor ve kodda 3 tane print olmasına rağmen uyarı ekranında 5 print bulunduğu yazıyor. 
![Ekran Görüntüsü (66)](https://user-images.githubusercontent.com/92365234/162316863-eaf247b0-70d2-4f49-9c35-05d34e2afff5.png)

**Comment by aysegul-hatipoglu** [comment]
düzeltildi.
